### ISSUE TITLE
Update Project Name in Client Library Documentation

### ISSUE THREAD

**Issue by parthea** [googleapis/python-runtimeconfig#12]
Hello,

While browsing the client library documentation for [google-cloud-runtimeconfig](https://googleapis.dev/python/runtimeconfig/latest/index.html), I noticed that the project name says `google-cloud-automl` instead of `google-cloud-runtimeconfig`.

![image](https://user-images.githubusercontent.com/5184014/80801477-8a40e080-8b7a-11ea-8643-475ae5e4c727.png)

**Comment by busunkim96** [comment]
@parthea Thank you for filing an issue! I re-built the docs locally and it looks like this has been fixed in our configs (but not released). 

I will keep this open until the library has been released with the changes.

![image](https://user-images.githubusercontent.com/8822365/80825862-0e549180-8b96-11ea-9e81-b2880106c6cb.png)

**Comment by tseaver** [comment]
Looks like this issue was fixed with the `v0.31.0` release.
